/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/spiderman.glb 
Author: Spiderware (https://sketchfab.com/Spiderware)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spider-man-spider-man-no-way-home-2cb11e591cc44357bffc6e23931a78e2
Title: Spider-man (Spider-man: No way Home)
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Group, SkinnedMesh, Vector3 } from 'three'
import { useControls } from 'leva'
import { useFrame } from '@react-three/fiber'
import useControlsChar from '../hooks/useControls'

export default function Spiderman() {
  const group = useRef<Group>(null)
  const { nodes, materials, animations } = useGLTF('/spiderman.glb')
  const { actions } = useAnimations(animations, group)

  console.log(actions)

  // Define the animation names
  const animationNames = [
    'Armature|Armature|hero_spiderman01_S08@atk-01|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@atk-02|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@dash|Base Layer', //dash with shift
    'Armature|Armature|hero_spiderman01_S08@die|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@hit|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@idle|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill01|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill02|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill03|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill04|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill05-01|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill05-02|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill05-03|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill06_cam|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@skill06|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@stun|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@succ_cam|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@wait|Base Layer',
    'Armature|Armature|hero_spiderman01_S08@walk|Base Layer', //normal walk with WASD
  ]

  // Leva controls for animations
  const { timeScale } = useControls('SPeed', {
    timeScale: {
      value: 1,
      min: 0,
      max: 3,
      step: 0.1,
      label: 'Time Scale',
    },
  })

  useEffect(() => {
    Object.values(actions).forEach((action) => {
      action!.setEffectiveTimeScale(timeScale)
    })
  }, [actions, timeScale])
  animationNames.forEach((name) => {
    useControls('player controls', {
      [name]: {
        value: false,
        label: name,

        onChange: (value) => handleAnimationPlay(name, value),
      },
    })
  })

  const handleAnimationPlay = (name: string, play: boolean) => {
    if (play) {
      actions[name]?.reset().play()
    } else {
      actions[name]?.stop()
    }
  }

  const { forward, backward, left, right } = useControlsChar()
  useFrame((_state, delta) => {
    if (!group.current) return

    const baseSpeed = 10

    const adjustedSpeed = baseSpeed * delta

    const direction = new Vector3(0, 0, 0)

    if (backward) direction.z += adjustedSpeed
    if (forward) direction.z -= adjustedSpeed
    if (right) direction.x += adjustedSpeed
    if (left) direction.x -= adjustedSpeed

    if (direction.lengthSq() > 0) {
      direction.normalize()

      const angle = Math.atan2(direction.x, direction.z)

      group.current.rotation.y = angle
    }

    group.current.position.add(direction)
  })

  return (
    <group scale={10} ref={group} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.12}
        >
          <group
            name="Spider-man_(Integrated_Suit)fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_148"
                      position={[100, 4, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_150"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_152"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_154"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_156"
                      position={[-100, 4, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_158"
                      position={[-266.612, 4, 0.478]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_160"
                      position={[0, 136.869, -9.593]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={80}
                    />
                    <skinnedMesh
                      name="Object_149"
                      geometry={(nodes.Object_149 as SkinnedMesh).geometry}
                      material={materials.SpiderMan_web02}
                      skeleton={(nodes.Object_149 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_151"
                      geometry={(nodes.Object_151 as SkinnedMesh).geometry}
                      material={materials.hero_spiderman01_s08_02}
                      skeleton={(nodes.Object_151 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_153"
                      geometry={(nodes.Object_153 as SkinnedMesh).geometry}
                      material={materials.hero_spiderman01_s08_01}
                      skeleton={(nodes.Object_153 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_155"
                      geometry={(nodes.Object_155 as SkinnedMesh).geometry}
                      material={materials.hero_spiderman01_s08_03}
                      skeleton={(nodes.Object_155 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_157"
                      geometry={(nodes.Object_157 as SkinnedMesh).geometry}
                      material={materials.SpiderMan_web02}
                      skeleton={(nodes.Object_157 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_159"
                      geometry={(nodes.Object_159 as SkinnedMesh).geometry}
                      material={materials.manhole}
                      skeleton={(nodes.Object_159 as SkinnedMesh).skeleton}
                    />
                  </group>
                </group>
                <group
                  name="spider_wp003"
                  position={[100, 4, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_02"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_01"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_03"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="spider_wp02"
                  position={[-100, 4, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="manhole"
                  position={[-266.612, 4, 0.478]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_wp"
                  position={[0, 136.869, -9.593]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={80}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spiderman.glb')
