/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/spiderman.glb 
Author: Spiderware (https://sketchfab.com/Spiderware)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spider-man-spider-man-no-way-home-2cb11e591cc44357bffc6e23931a78e2
Title: Spider-man (Spider-man: No way Home)
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Group, SkinnedMesh } from 'three'
import { useControls } from 'leva'
import { animationNames } from '../consts/animations'
import useCharacterControls from '../hooks/useCharacterControls'

export default function Spiderman() {
  const group = useRef<Group>(null)
  const { nodes, materials, animations } = useGLTF('/spiderman.glb')
  const { actions } = useAnimations(animations, group)

  useCharacterControls(group, animations)

  //debug{
  const { timeScale } = useControls('Speed', {
    timeScale: {
      value: 1,
      min: 0,
      max: 3,
      step: 0.1,
      label: 'Time Scale',
    },
  })

  useEffect(() => {
    Object.values(actions).forEach((action) => {
      action!.setEffectiveTimeScale(timeScale)
    })
  }, [actions, timeScale])

  // Adjust Leva panel controls for animations
  animationNames.forEach((fullName) => {
    const name = fullName.slice(39, 52)
    useControls('animations', {
      [fullName]: {
        value: false,
        label: name,
        onChange: (value) => handleAnimationPlay(fullName, value),
      },
    })
  })

  const handleAnimationPlay = (fullName: string, play: boolean) => {
    // Stop all animations first
    Object.values(actions).forEach((action) => {
      action!.stop()
    })

    // Play the selected animation
    if (play) {
      actions[fullName]?.reset().play()
    }
  }

  //}
  return (
    <group scale={10} ref={group} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.12}
        >
          <group
            name="Spider-man_(Integrated_Suit)fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_148"
                      position={[100, 4, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_150"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_152"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_154"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_156"
                      position={[-100, 4, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_158"
                      position={[-266.612, 4, 0.478]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_160"
                      position={[0, 136.869, -9.593]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={80}
                    />
                    <skinnedMesh
                      name="Object_149"
                      geometry={(nodes.Object_149 as SkinnedMesh).geometry}
                      material={materials.SpiderMan_web02}
                      skeleton={(nodes.Object_149 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_151"
                      geometry={(nodes.Object_151 as SkinnedMesh).geometry}
                      material={materials.hero_spiderman01_s08_02}
                      skeleton={(nodes.Object_151 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_153"
                      geometry={(nodes.Object_153 as SkinnedMesh).geometry}
                      material={materials.hero_spiderman01_s08_01}
                      skeleton={(nodes.Object_153 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_155"
                      geometry={(nodes.Object_155 as SkinnedMesh).geometry}
                      material={materials.hero_spiderman01_s08_03}
                      skeleton={(nodes.Object_155 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_157"
                      geometry={(nodes.Object_157 as SkinnedMesh).geometry}
                      material={materials.SpiderMan_web02}
                      skeleton={(nodes.Object_157 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_159"
                      geometry={(nodes.Object_159 as SkinnedMesh).geometry}
                      material={materials.manhole}
                      skeleton={(nodes.Object_159 as SkinnedMesh).skeleton}
                    />
                  </group>
                </group>
                <group
                  name="spider_wp003"
                  position={[100, 4, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_02"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_01"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_03"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="spider_wp02"
                  position={[-100, 4, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="manhole"
                  position={[-266.612, 4, 0.478]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_wp"
                  position={[0, 136.869, -9.593]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={80}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spiderman.glb')
