export const animationNames = [
  'Armature|Armature|hero_spiderman01_S08@atk-01|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@atk-02|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@dash|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@die|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@hit|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@idle|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill01|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill02|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill03|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill04|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill05-01|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill05-02|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill05-03|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill06_cam|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@skill06|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@stun|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@succ_cam|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@wait|Base Layer',
  'Armature|Armature|hero_spiderman01_S08@walk|Base Layer',
]
